version: "3.9"
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "SistemaComedorCompose"
    restart: always
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DRIVER=mysql
      - HOST=mysql_container
      - USER=mastercomedor
      - PASS=undccomedor$
      - DATABASE=sistemacomedor
      - PORT=3306
       #- VIRTUAL_HOST=182.160.24.51
       #- LETSENCRYPT_HOST=182.160.24.51
    networks:
      - sistema_comedor_network

  db:
    image: mysql:latest
    container_name: "mysql_container"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "undccomedor$"
      MYSQL_DATABASE: "sistemacomedor"
      MYSQL_USER: "mastercomedor"
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d   # Monta el directorio 'database'
    networks:
      - sistema_comedor_network      

volumes:
  SistemaComedorCompose:
  db_data:

networks:
  proxy:
  sistema_comedor_network:
    name: sistema_comedor_network
